# This was built in Step 2.
FROM codewarrior23/personal-repository:wildfly-step2

# Copy the Java Jar files into the JBoss ./lib directory.
COPY target/sb-jboss-example*.war     /opt/jboss/wildfly/standalone/deployments/SpringBootJboss.war