# This was built in Step 1.
FROM codewarrior23/personal-repository:wildfly-step2

# Copy the Java Jar files into the JBoss ./lib directory.
COPY target/spboot-0.0.1-SNAPSHOT.jar.original     /opt/jboss/wildfly/standalone/deployments/spboot-0.0.1-SNAPSHOT.jar
